"""empty message

Revision ID: 85de1da50303
Revises: 999aacf57e59
Create Date: 2025-08-03 21:20:14.195794

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "85de1da50303"
down_revision: str | Sequence[str] | None = "999aacf57e59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
