"""empty message

Revision ID: 908a36c712dc
Revises: 85de1da50303
Create Date: 2025-08-03 21:23:52.808778

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "908a36c712dc"
down_revision: str | Sequence[str] | None = "85de1da50303"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticker_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticker_history_active"), "ticker_history", ["active"], unique=False
    )
    op.create_index(
        op.f("ix_ticker_history_company_id"),
        "ticker_history",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticker_history_symbol"), "ticker_history", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_ticker_history_valid_from"),
        "ticker_history",
        ["valid_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticker_history_valid_to"), "ticker_history", ["valid_to"], unique=False
    )
    op.create_table(
        "tickers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tickers_company_id"), "tickers", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_tickers_symbol"), "tickers", ["symbol"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickers_symbol"), table_name="tickers")
    op.drop_index(op.f("ix_tickers_company_id"), table_name="tickers")
    op.drop_table("tickers")
    op.drop_index(op.f("ix_ticker_history_valid_to"), table_name="ticker_history")
    op.drop_index(op.f("ix_ticker_history_valid_from"), table_name="ticker_history")
    op.drop_index(op.f("ix_ticker_history_symbol"), table_name="ticker_history")
    op.drop_index(op.f("ix_ticker_history_company_id"), table_name="ticker_history")
    op.drop_index(op.f("ix_ticker_history_active"), table_name="ticker_history")
    op.drop_table("ticker_history")
    # ### end Alembic commands ###
