"""add tickers and ticker_history

Revision ID: 999aacf57e59
Revises: c35a8cf0bca6
Create Date: 2025-08-03 21:18:13.384595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999aacf57e59'
down_revision: Union[str, Sequence[str], None] = 'c35a8cf0bca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
