"""update companies, and add tickers and ticker_history

Revision ID: c35a8cf0bca6
Revises: a81b1a8ca21c
Create Date: 2025-08-03 21:12:22.073749

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c35a8cf0bca6"
down_revision: str | Sequence[str] | None = "a81b1a8ca21c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_companies_ticker"), table_name="companies")
    op.drop_column("companies", "ticker")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column("ticker", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.create_index(op.f("ix_companies_ticker"), "companies", ["ticker"], unique=True)
    # ### end Alembic commands ###
